### ISSUE TITLE
Can't spectate duel match

### ISSUE THREAD

**Issue by SirvydasS** [RealizedMC/Duels#101]
Getting errors when trying to spectate a match.

> │[10:34:24 INFO]: Krepxinx issued server command: /duels:spectate Test                                                                                                                                ││[10:34:24 ERROR]: null                                                                                                                                                                               ││org.bukkit.command.CommandException: Unhandled exception executing command 'duels:spectate' in plugin Duels v3.5.3                                                                                   ││at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]                                                                                          ││at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]                                                                                  ││at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                            ││at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                               ││at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]                                                                                                 ││at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]                                                                                                                          ││at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]                                                                                                                          ││at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]                                                                       ││at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2342) ~[?:?]                                                              ││at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]                                                                                              ││at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]                                                                                                        ││at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                                          ││at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]                                                                                                        ││at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]                                                                                       ││at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                    ││at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                             ││at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]                                                                                                         ││at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                             │
│at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                     ││at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]                                                                                                      ││at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                   │
│at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                    ││at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1965]                                                                                 ││at java.lang.Thread.run(Thread.java:1623) ~[?:?]                                                                                                                                                     │
│Caused by: java.lang.NullPointerException: Cannot invoke "me.realized.duels.hook.hooks.EssentialsHook.isVanished(org.bukkit.entity.Player)" because "this.essentials" is null                        ││at me.realized.duels.spectate.SpectateManagerImpl.startSpectating(SpectateManagerImpl.java:142) ~[Duels-3.5.3.jar:?]                                                                                 │
│at me.realized.duels.command.commands.SpectateCommand.execute(SpectateCommand.java:50) ~[Duels-3.5.3.jar:?]                                                                                          ││at me.realized.duels.util.command.AbstractCommand.lambda$register$6(AbstractCommand.java:143) ~[Duels-3.5.3.jar:?]                                                                                   │
│at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]                                                                                          ││... 23 more

**Comment by qualk** [comment]
This error is occurring because you are vanished. I believe this is a duplicate of #87 and that #100 fixes it.
