### ISSUE TITLE
Essentials Issue

### ISSUE THREAD

**Issue by AhmHkn0** [RealizedMC/Duels#116]
I don't use Essentials plugin. But this Duels plugin require Essentials. I don't want to use the Essentials plugin, I need this plugin to control that.

```
[06:01:48 INFO]: PoyrazOglu issued server command: /duels:spec AhmHkn
[06:01:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'duel
s:spec' in plugin Duels v3.5.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pur
pur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:16
8) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServ
er.java:1005) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(Bukk
itCommandWrapper.java:64) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java
:265) ~[purpur-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:338) ~[?
:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?
:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChat
Command(ServerGamePacketListenerImpl.java:2279) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$hand
leChatCommand$20(ServerGamePacketListenerImpl.java:2239) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(Blo
ckableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFut
ure.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.j
ar:git-Purpur-2094]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEvent
Loop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(Reent
rantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1
351) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[pu
rpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventL
oop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer
.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:13
21) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEv
entLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServe
r.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1
187) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.ja
va:320) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.realized.duels.hook
.hooks.EssentialsHook.isVanished(org.bukkit.entity.Player)" because "this.essent
ials" is null
        at me.realized.duels.spectate.SpectateManagerImpl.startSpectating(Specta
teManagerImpl.java:142) ~[Duels-3.5.3.jar:?]
        at me.realized.duels.command.commands.SpectateCommand.execute(SpectateCo
mmand.java:50) ~[Duels-3.5.3.jar:?]
        at me.realized.duels.util.command.AbstractCommand.lambda$register$6(Abst
ractCommand.java:143) ~[Duels-3.5.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pur
pur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by anmvc** [comment]
This is a version issue, not a essentialsx issue.
Edit: Nvm.

**Comment by sprytex** [comment]
Fixed here: https://modrinth.com/plugin/duelsoptimized/version/3.5.4
